version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
    networks:
      - fcfx

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    ports:
      - 3307:3306  
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - fcfx

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    ports:
      - 9000:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - fcfx

networks:
  fcfx:
    external: true